baseURL = "https://markbeachill.github.io/site01/"
languageCode = "en-gb"
title = "MyStuff"
theme = "PaperMod"
publishDir = "docs"




# Enable HTML in content files
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

# Navigation menu
[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "pages"
    name = "Pages"
    url = "/pages/"
    weight = 2
  [[menu.main]]
    identifier = "general"
    name = "General"
    url = "/general/"
    weight = 3
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 4